import {describe,expect,it} from 'vitest';
import {createRectangle,createTriangle} from '../core/document';
import {localBounds,localToWorld,objectCenter,worldToLocal} from './geometry';
import {exceedsDragThreshold,rebaseAfterGeometryChange,resizeAlongLocalEdge,resizeFromLocalCorner,resizeProportionallyAroundWorld,transformAround,transformKeepingLocalPoint,type Corner} from './transform';
describe('world-centred selection transforms',()=>{it('keeps the pivot fixed while scaling and rotating',()=>{const object=createTriangle(400,260),pivot=objectCenter(object),after=transformAround(object,object.transform,pivot,2,Math.PI/4),changed={...object,transform:after};expect(objectCenter(changed).x).toBeCloseTo(pivot.x);expect(objectCenter(changed).y).toBeCloseTo(pivot.y);expect(after.rotation).toBeCloseTo(Math.PI/4);expect(after.scaleX).toBeCloseTo(2);});it('adds rotation deltas to an already rotated object without jumping',()=>{const object=createTriangle(20,40),first={...object.transform,rotation:Math.PI/4},pivot=objectCenter({...object,transform:first}),second=transformAround(object,first,pivot,1,Math.PI/6);expect(second.rotation).toBeCloseTo(Math.PI*5/12);expect(objectCenter({...object,transform:second})).toEqual(pivot);});});

describe('current-oriented resizing',()=>{
  for(const degrees of [0,27,45,90,135])it(`keeps the opposite edge fixed at ${degrees}°`,()=>{const rectangle=createRectangle(120,80),before={...rectangle.transform,scaleX:1.4,scaleY:.7,rotation:degrees*Math.PI/180},source={...rectangle,transform:before},fixedBefore=localToWorld(source,0,70),right=localToWorld(source,270,70),after=resizeAlongLocalEdge(rectangle,before,'right',right),changed={...rectangle,transform:after},fixedAfter=localToWorld(changed,0,70);expect(fixedAfter.x).toBeCloseTo(fixedBefore.x,8);expect(fixedAfter.y).toBeCloseTo(fixedBefore.y,8);expect(after.rotation).toBeCloseTo(before.rotation);});

  it('keeps the visible bottom-right corner fixed through flipped, rotated stretching',()=>{const rectangle=createRectangle(300,180),before={...rectangle.transform,scaleX:-1.25,scaleY:.65,rotation:Math.PI*3/4},source={...rectangle,transform:before},bounds=localBounds(source),corner={x:bounds.x+bounds.width,y:bounds.y+bounds.height},fixed=localToWorld(source,corner.x,corner.y),pointer=localToWorld(source,bounds.x-80,bounds.y+bounds.height/2),after=resizeAlongLocalEdge(rectangle,before,'left',pointer,'bottomRight'),changed={...rectangle,transform:after},stillFixed=localToWorld(changed,corner.x,corner.y);expect(stillFixed.x).toBeCloseTo(fixed.x,8);expect(stillFixed.y).toBeCloseTo(fixed.y,8);expect(after.scaleX).toBeCloseTo(-1.25*260/180,8);});

  it('preserves a chosen world anchor while both local scales change',()=>{const triangle=createTriangle(10,20),before={...triangle.transform,scaleX:1.8,scaleY:-.6,rotation:.47},source={...triangle,transform:before},fixedLocal={x:180,y:160},fixedWorld=localToWorld(source,fixedLocal.x,fixedLocal.y),after=transformKeepingLocalPoint(triangle,before,fixedLocal,fixedWorld,.9,-1.7),changed={...triangle,transform:after},actual=localToWorld(changed,fixedLocal.x,fixedLocal.y);expect(actual.x).toBeCloseTo(fixedWorld.x,8);expect(actual.y).toBeCloseTo(fixedWorld.y,8);const roundTrip=worldToLocal(changed,actual.x,actual.y);expect(roundTrip.x).toBeCloseTo(fixedLocal.x,8);expect(roundTrip.y).toBeCloseTo(fixedLocal.y,8);});

  for(const degrees of [0,27,45,90,135])for(const movingCorner of ['topLeft','topRight','bottomRight','bottomLeft'] as Corner[])it(`scales proportionally from ${movingCorner} with its opposite fixed at ${degrees}°`,()=>{const rectangle=createRectangle(75,125),before={...rectangle.transform,scaleX:degrees===90?-1.35:1.35,scaleY:.65,rotation:degrees*Math.PI/180},source={...rectangle,transform:before},bounds=localBounds(source),points={topLeft:{x:bounds.x,y:bounds.y},topRight:{x:bounds.x+bounds.width,y:bounds.y},bottomRight:{x:bounds.x+bounds.width,y:bounds.y+bounds.height},bottomLeft:{x:bounds.x,y:bounds.y+bounds.height}},opposites={topLeft:'bottomRight',topRight:'bottomLeft',bottomRight:'topLeft',bottomLeft:'topRight'} as const,movingLocal=points[movingCorner],fixedLocal=points[opposites[movingCorner]],movingWorld=localToWorld(source,movingLocal.x,movingLocal.y),fixedBefore=localToWorld(source,fixedLocal.x,fixedLocal.y),factor=1.4,pointer={x:fixedBefore.x+(movingWorld.x-fixedBefore.x)*factor,y:fixedBefore.y+(movingWorld.y-fixedBefore.y)*factor},after=resizeFromLocalCorner(rectangle,before,pointer,movingCorner,movingWorld),changed={...rectangle,transform:after},fixedAfter=localToWorld(changed,fixedLocal.x,fixedLocal.y);expect(after.scaleX).toBeCloseTo(before.scaleX*factor,8);expect(after.scaleY).toBeCloseTo(before.scaleY*factor,8);expect(after.scaleX/after.scaleY).toBeCloseTo(before.scaleX/before.scaleY,8);expect(fixedAfter.x).toBeCloseTo(fixedBefore.x,8);expect(fixedAfter.y).toBeCloseTo(fixedBefore.y,8);});

  it('scales current geometry proportionally around an arbitrary selection-frame corner',()=>{const rectangle=createRectangle(50,60),before={...rectangle.transform,scaleX:1.7,scaleY:.6,rotation:.81},pivot={x:10,y:20},start={x:210,y:180},pointer={x:310,y:260},after=resizeProportionallyAroundWorld(rectangle,before,pivot,start,pointer),sourceCenter=objectCenter({...rectangle,transform:before}),changedCenter=objectCenter({...rectangle,transform:after}),factor=((pointer.x-pivot.x)*(start.x-pivot.x)+(pointer.y-pivot.y)*(start.y-pivot.y))/((start.x-pivot.x)**2+(start.y-pivot.y)**2);expect(after.scaleX).toBeCloseTo(before.scaleX*factor,8);expect(after.scaleY).toBeCloseTo(before.scaleY*factor,8);expect(changedCenter.x).toBeCloseTo(pivot.x+(sourceCenter.x-pivot.x)*factor,8);expect(changedCenter.y).toBeCloseTo(pivot.y+(sourceCenter.y-pivot.y)*factor,8);});

  it('does not jump when a padded corner or side handle first moves',()=>{const rectangle=createRectangle(30,40),before={...rectangle.transform,scaleX:-1.2,scaleY:.8,rotation:.61},cornerStart={x:99,y:87},corner=resizeFromLocalCorner(rectangle,before,cornerStart,'bottomRight',cornerStart),sideStart={x:122,y:76},side=resizeAlongLocalEdge(rectangle,before,'top',sideStart,'bottomRight',sideStart);expect(corner).toEqual(before);expect(side).toEqual(before);});
});

describe('geometry rebasing in Node Mode',()=>{
  for(const degrees of [0,27,45,90,135])it(`preserves the existing affine mapping when path bounds change at ${degrees}°`,()=>{const beforeObject=createTriangle(210,95),transformed={...beforeObject,transform:{...beforeObject.transform,scaleX:degrees===135?-1.45:1.45,scaleY:.72,rotation:degrees*Math.PI/180}};if(transformed.geometry.kind!=='path')throw new Error('Expected path');const moved={...transformed.geometry.nodes[0],anchor:{x:-75,y:-110}},changed={...transformed,geometry:{...transformed.geometry,nodes:[moved,...transformed.geometry.nodes.slice(1)]}},after=rebaseAfterGeometryChange(transformed,changed);if(after.geometry.kind!=='path')throw new Error('Expected path');for(const node of after.geometry.nodes){const expected=localToWorld(transformed,node.anchor.x,node.anchor.y),actual=localToWorld(after,node.anchor.x,node.anchor.y),roundTrip=worldToLocal(after,actual.x,actual.y);expect(actual.x).toBeCloseTo(expected.x,8);expect(actual.y).toBeCloseTo(expected.y,8);expect(roundTrip.x).toBeCloseTo(node.anchor.x,8);expect(roundTrip.y).toBeCloseTo(node.anchor.y,8);}});
});

describe('transform histories',()=>{
  for(const name of ['rotate-resize','resize-rotate','stretch-rotate-resize','rotate-anchor-resize','flip-rotate-resize','move-rotate-stretch','repeated-transforms'])it(`keeps transforms coherent through ${name}`,()=>{const rectangle=createRectangle(140,220),start={...rectangle.transform,scaleX:name.startsWith('flip')?-1:1,scaleY:1,rotation:0},pivot=objectCenter({...rectangle,transform:start});let current=start;const rotate=()=>{current=transformAround(rectangle,current,pivot,1,.43);};const scale=()=>{current=transformAround(rectangle,current,pivot,1.18,0);};const stretch=()=>{const source={...rectangle,transform:current},bounds=localBounds(source),fixed={x:bounds.x+bounds.width,y:bounds.y+bounds.height},moving=localToWorld(source,bounds.x,bounds.y+bounds.height/2),cos=Math.cos(current.rotation),sin=Math.sin(current.rotation),pointer={x:moving.x-45*cos,y:moving.y-45*sin};current=resizeAlongLocalEdge(rectangle,current,'left',pointer,'bottomRight');const actual=localToWorld({...rectangle,transform:current},fixed.x,fixed.y),expected=localToWorld(source,fixed.x,fixed.y);expect(actual.x).toBeCloseTo(expected.x,8);expect(actual.y).toBeCloseTo(expected.y,8);};const anchorResize=()=>{const source={...rectangle,transform:current},bounds=localBounds(source),moving=localToWorld(source,bounds.x,bounds.y),pointer={x:moving.x-25,y:moving.y-30};current=resizeFromLocalCorner(rectangle,current,pointer,'bottomRight');};if(name==='rotate-resize'){rotate();scale();}else if(name==='resize-rotate'){scale();rotate();}else if(name==='stretch-rotate-resize'){stretch();rotate();scale();}else if(name==='rotate-anchor-resize'){rotate();anchorResize();}else if(name==='flip-rotate-resize'){rotate();scale();}else if(name==='move-rotate-stretch'){current={...current,x:current.x+70,y:current.y-35};rotate();stretch();}else for(let index=0;index<6;index+=1){rotate();scale();stretch();}const changed={...rectangle,transform:current};for(const point of [{x:0,y:0},{x:180,y:0},{x:180,y:140},{x:0,y:140}]){const world=localToWorld(changed,point.x,point.y),local=worldToLocal(changed,world.x,world.y);expect(Number.isFinite(world.x)&&Number.isFinite(world.y)).toBe(true);expect(local.x).toBeCloseTo(point.x,7);expect(local.y).toBeCloseTo(point.y,7);}});
});

describe('pointer gesture intent',()=>{it('keeps sub-threshold movement as a tap',()=>{expect(exceedsDragThreshold(5,6,8)).toBe(false);expect(exceedsDragThreshold(8,0,8)).toBe(false);});it('becomes a drag only beyond the threshold',()=>{expect(exceedsDragThreshold(8.01,0,8)).toBe(true);expect(exceedsDragThreshold(7,7,8)).toBe(true);});});
