import {describe,expect,it} from 'vitest';
import {createRectangle,createTriangle} from '../core/document';
import {localBounds,localToWorld,objectCenter,worldToLocal} from './geometry';
import {exceedsDragThreshold,resizeAlongLocalEdge,transformAround,transformKeepingLocalPoint} from './transform';
describe('world-centred selection transforms',()=>{it('keeps the pivot fixed while scaling and rotating',()=>{const object=createTriangle(400,260),pivot=objectCenter(object),after=transformAround(object,object.transform,pivot,2,Math.PI/4),changed={...object,transform:after};expect(objectCenter(changed).x).toBeCloseTo(pivot.x);expect(objectCenter(changed).y).toBeCloseTo(pivot.y);expect(after.rotation).toBeCloseTo(Math.PI/4);expect(after.scaleX).toBeCloseTo(2);});it('adds rotation deltas to an already rotated object without jumping',()=>{const object=createTriangle(20,40),first={...object.transform,rotation:Math.PI/4},pivot=objectCenter({...object,transform:first}),second=transformAround(object,first,pivot,1,Math.PI/6);expect(second.rotation).toBeCloseTo(Math.PI*5/12);expect(objectCenter({...object,transform:second})).toEqual(pivot);});});

describe('current-oriented resizing',()=>{
  for(const degrees of [0,27,45,90,135])it(`keeps the opposite edge fixed at ${degrees}°`,()=>{const rectangle=createRectangle(120,80),before={...rectangle.transform,scaleX:1.4,scaleY:.7,rotation:degrees*Math.PI/180},source={...rectangle,transform:before},fixedBefore=localToWorld(source,0,70),right=localToWorld(source,270,70),after=resizeAlongLocalEdge(rectangle,before,'right',right),changed={...rectangle,transform:after},fixedAfter=localToWorld(changed,0,70);expect(fixedAfter.x).toBeCloseTo(fixedBefore.x,8);expect(fixedAfter.y).toBeCloseTo(fixedBefore.y,8);expect(after.rotation).toBeCloseTo(before.rotation);});

  it('keeps the visible bottom-right corner fixed through flipped, rotated stretching',()=>{const rectangle=createRectangle(300,180),before={...rectangle.transform,scaleX:-1.25,scaleY:.65,rotation:Math.PI*3/4},source={...rectangle,transform:before},bounds=localBounds(source),corner={x:bounds.x+bounds.width,y:bounds.y+bounds.height},fixed=localToWorld(source,corner.x,corner.y),pointer=localToWorld(source,bounds.x-80,bounds.y+bounds.height/2),after=resizeAlongLocalEdge(rectangle,before,'left',pointer,'bottomRight'),changed={...rectangle,transform:after},stillFixed=localToWorld(changed,corner.x,corner.y);expect(stillFixed.x).toBeCloseTo(fixed.x,8);expect(stillFixed.y).toBeCloseTo(fixed.y,8);expect(after.scaleX).toBeCloseTo(-1.25*260/180,8);});

  it('preserves a chosen world anchor while both local scales change',()=>{const triangle=createTriangle(10,20),before={...triangle.transform,scaleX:1.8,scaleY:-.6,rotation:.47},source={...triangle,transform:before},fixedLocal={x:180,y:160},fixedWorld=localToWorld(source,fixedLocal.x,fixedLocal.y),after=transformKeepingLocalPoint(triangle,before,fixedLocal,fixedWorld,.9,-1.7),changed={...triangle,transform:after},actual=localToWorld(changed,fixedLocal.x,fixedLocal.y);expect(actual.x).toBeCloseTo(fixedWorld.x,8);expect(actual.y).toBeCloseTo(fixedWorld.y,8);const roundTrip=worldToLocal(changed,actual.x,actual.y);expect(roundTrip.x).toBeCloseTo(fixedLocal.x,8);expect(roundTrip.y).toBeCloseTo(fixedLocal.y,8);});
});

describe('pointer gesture intent',()=>{it('keeps sub-threshold movement as a tap',()=>{expect(exceedsDragThreshold(5,6,8)).toBe(false);expect(exceedsDragThreshold(8,0,8)).toBe(false);});it('becomes a drag only beyond the threshold',()=>{expect(exceedsDragThreshold(8.01,0,8)).toBe(true);expect(exceedsDragThreshold(7,7,8)).toBe(true);});});
